# Generated by Django 3.1 on 2020-11-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blogs'},
        ),
    ]
