# Generated by Django 3.1 on 2020-11-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0002_auto_20201102_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_title',
            new_name='title',
        ),
    ]
