# Generated by Django 3.1.2 on 2020-11-07 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0003_auto_20201102_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuhub.blog')),
            ],
        ),
    ]
