# Generated by Django 3.1.1 on 2020-11-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0004_comment'),
        ('kuhub', '0005_blog_dislikes'),
    ]

    operations = [
    ]
