# Generated by Django 3.1.1 on 2020-11-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0006_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
