# Generated by Django 3.1.1 on 2020-11-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0007_report_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='text',
        ),
    ]
