# Generated by Django 3.1.1 on 2020-11-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0009_report_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(default=None),
        ),
    ]
