# Generated by Django 3.1.1 on 2020-11-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0010_auto_20201108_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(),
        ),
    ]
