# Generated by Django 3.1.1 on 2020-11-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0012_report_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(default='', null=True),
        ),
    ]
