# Generated by Django 3.1.1 on 2020-11-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0013_auto_20201108_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
