# Generated by Django 3.1.1 on 2020-11-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0015_auto_20201108_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogreport',
            name='topic',
            field=models.CharField(choices=[('Fake new', 'Fake new'), ('Spam', 'Spam'), ('Create conflict', 'Create conflict'), ('Threat', 'Threat'), ('Violence', 'Violence'), ('Indecent words', 'Indecent words'), ('Sexual Harassment', 'Sexual Harassment'), ('Others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='topic',
            field=models.CharField(choices=[('Fake new', 'Fake new'), ('Spam', 'Spam'), ('Create conflict', 'Create conflict'), ('Threat', 'Threat'), ('Violence', 'Violence'), ('Indecent words', 'Indecent words'), ('Sexual Harassment', 'Sexual Harassment'), ('Others', 'Others')], max_length=20),
        ),
    ]
