language: python

python: 3.7.3

git:
  depth: 1

install:
  - pip install -r requirements.txt

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py collectstatic
  - coverage run manage.py test

after_script:
  - bash <(curl -s https://codecov.io/bash)